### ISSUE TITLE
Lấy yêu cầu khách hàng

### ISSUE THREAD

**Issue by NguyenTien243** [NguyenTien243/ProjectSE#1]
1. go

**Comment by NguyenTien243** [comment]
https://github.com/NguyenTien243/ProjectSE/blob/main/report/Nhom11_BaiTapDeXuatYeuCauCanThucHienChoDeTai.pdf

**Comment by B-Phuong** [comment]
[Nhom11_BaiTapDeXuatYeuCauCanThucHienChoDeTai.docx](https://github.com/NguyenTien243/ProjectSE/files/6198401/Nhom11_BaiTapDeXuatYeuCauCanThucHienChoDeTai.docx)

**Comment by NguyenTien243** [comment]
https://github.com/NguyenTien243/ProjectSE/blob/dd25122c997069f8d2ba2d04b2d4903b9645b5bf/report/Nhom11_BaiTapDeXuatYeuCauCanThucHienChoDeTai.pdf

**Comment by NguyenTien243** [comment]
[Nhom11_BaiTapDeXuatYeuCauCanThucHienChoDeTai (1).docx](https://github.com/NguyenTien243/ProjectSE/files/6198442/Nhom11_BaiTapDeXuatYeuCauCanThucHienChoDeTai.1.docx)
