### ISSUE TITLE
2. Sử dụng bảng (mô tả action trong cách 1)

### ISSUE THREAD

**Issue by souldippy** [NguyenTien243/ProjectSE#10]

**Comment by NguyenTien243** [comment]
https://github.com/NguyenTien243/ProjectSE/blob/main/report/DactaCNPM_dangbang.pdf

**Comment by NguyenTien243** [comment]
https://github.com/NguyenTien243/ProjectSE/blob/main/report/DactaCNPM_dangbang.docx
