### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by B-Phuong** [NguyenTien243/ProjectSE#7]

**Comment by souldippy** [comment]
### **1. Đăng nhập** | Chức năng đăng nhập giúp người dùng đã có tài khoản đăng nhập vào hệ thống 
1.1. Chức năng đăng nhập gồm gồm 2 textbox để nhập thông tin tài khoản và mật khẩu, 1 button để xác nhận đăng nhập 
1.2. Sau khi đã xác nhận có nhập thông tin và nhấp vào “Đăng nhập” thì sẽ so sánh với dữ liệu xem có đúng không, nếu có thì sẽ đưa vào màn hình điều khiển của từng loại user còn nếu không thì sẽ thông báo ra màn hình 
1.3. Nếu nhập sai mật khẩu quá 5 lần sẽ bắt xác thực bằng captcha
### **2. Đăng ký** | Chức năng đăng ký giúp người dùng chưa có tài khoản đăng ký vào hệ thống
2.1. Có các textbox để nhập các thông tin cá nhân của user để lưu vào csdl 
2.2. Xác thực bằng captcha 
2.3. Câu hỏi và câu trả lời bảo mật 
### **3. Đăng ký vé giữ xe tháng** | Giúp người dùng đăng ký vé tháng
3.1. Có textbox để nhập số tháng muốn mua 
3.2. Hiển thị tổng số tiền cần thanh toán 
3.3. Xác thực bằng captcha 
3.4. Có các lựa chọn thanh toán 
3.5. Nếu click vào thanh toán bằng ngân hàng sẽ tự động chuyển đến web của ngân hàng đó rồi thanh toán. Sau đó chờ xác thực thanh toán 
3.6. Nếu click vào thanh toán trực tiếp thì sẽ chờ xác thực thanh toán 
3.7. Khi hoàn thành xác thực thì tài khoản thanh toán sẽ được cung cấp vé tháng theo số tháng mà mình muốn đăng ký 
### **4. Thống kê xe ra vào, xe hiện có trong bãi** | Hiển thị số lượng xe ra vào, hiện có
4.1. Chức năng này chỉ xuất hiện khi đang trong vai trò là nhân viên giữ xe trở lên 
4.2. Hiển thị chi tiết số lượng xe ra vào trong ngày/ tháng/ nằm ở label bên màn hình hiển thị 
4.3. Hiển thị số xe đang có trong bãi nằm ở label bên màn hình hiển thị
### **5. Quản lý thông tin user** | Giúp người dùng chỉnh sửa một số dữ liệu trong csdl
5.1. Ở góc màn hình sẽ hiển thị hình ảnh của user đã đăng nhập  
5.2. Khi click vào hình ảnh đó sẽ hiển thị một loạt lựa chọn như xem thông tin, chỉnh sửa thông tin, đăng xuất. 
5.3. Ở chức năng xem thông tin thì sẽ hiển thị những thông tin khi đăng kí của user 
5.4. Ở chức năng sửa thông tin thì cho phép chỉnh sửa các thông tin khi đăng kí của user 
### **6. Gửi xe** | Giúp khách hàng gửi xe
6.1. Textbox giúp nhập thông tin của xe khách hàng muốn gửi 
6.2. List giúp hiển thị những chỗ gửi xe còn trống để chọn 
6.3. Thông tin thời gian gửi 
6.4. Xác nhận gửi xe 
### **7. Lấy xe** | Giúp khách hàng lấy xe
7.1. Textbox giúp hiển thị thông tin của khách hàng 
7.2. Xác nhận thời gian lấy 
7.3. Tự động làm trống vị trí của khách hàng đã gửi khi ấn xác nhận lấy xe
### **8. Thống kê realtime** | Số xe, khách hàng hiện đang gửi xe 
8.1. Hiển thị số khách hàng đang gửi xe trong thời gian thực
8.2. Hiển thị số xe đang gửi trong thời gian thực
### **9. Tìm kiếm chỗ để xe trống** | Để xem bãi đậu xe đã còn chỗ hay đã đầy rồi 
9.1. Hệ thống sẽ dựa vào thông tin mà gửi xe để xác định chỗ trống của bãi 
9.2. Sau khi nhấn vào sẽ hiển thị vị trí chỗ trống ở khu bao nhiêu, ô bao nhiêu trên màn hình
### **10. Chức năng phân quyền quản trị** | Phân quyền cho quản lý, nhân viên, khách hàng,..
10.1. Trên màn hình sẽ hiển thị ra danh sách user và bảng lựa chọn user 
10.2. Khi nhấn vào button xác nhận đổi quyền thì vai trò của User sẽ thay đổi 
### **11. Lưu thời gian của xe đã ra/ vào bãi** | Giúp lưu những thông tin khi gửi xe vào csdl để đối chiếu sau này 
11.1. Sau khi xe xác nhận gửi hoặc rời khỏi bãi sẽ tự động lưu lại những thông tin như giờ ra vào,...
### **12. Thiết lập giá vé** | Giúp tạo ra loại vé mới hoặc thay đổi giá vé 
12.1Hiển thị các loại vé cần tạo như vé ngày, vé tháng,… 
12.2. Thêm loại vé hoặc thay đổi giá vé được nhập từ bàn phím
