### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by B-Phuong** [NguyenTien243/ProjectSE#8]

**Comment by NguyenTien243** [comment]
- Tối đa thông tin của 200 chiếc xe/ bãi.
- Đảm bảo dữ liệu khi có sự cố (vd: cúp điện)
- Thời gian thực thi 1 chức năng không quá 1s.

**Comment by NguyenTien243** [comment]
bản chỉnh sữa: 
Số lượng xe tối đa cùng ở trong bãi là 200 chiếc.
Đảm bảo dữ liệu khi có sự cố (vd: cúp điện thì có nguồn dự trữ)
Thời gian thực thi 1 chức năng không quá 1s.
Thời gian khởi động hệ thống không quá 1 phút.
Thời gian ghi nhận thông tin xe ra vào không quá 5s. (nhận tín hiệu thẻ từ thiết bị RFID)
Thêm thẻ giữ xe mới vào hệ thống (có thể tăng thêm số lượng thẻ giữ xe trường hợp khách hàng làm mất thẻ)
Appication sử dụng trên hệ điều hành Window, ngôn ngữ C# Winform hoặc WPF.
Số lượng lỗi <= 3 lỗi trên mỗi giờ sử dụng.
Sau 1h training có thể sử dụng được hệ thống.
Thời gian khởi động lại hệ thống khi gặp lỗi không quá 3 phút (lỗi hệ điều hành, lỗi phần cứng...)
Tài khoản đăng ký phải có thẻ cmnd/căn cước.
